### ISSUE TITLE
Error reading data

### ISSUE THREAD

**Issue by colingoldberg** [rhiever/tpot#290] opened 2016-10-08 13:00 UTC
Hi,

In trying to run tpot - on an AWS EC2 instance - I get an error which appears to be a buffer size issue (in numpy?)

$tpot numerai_training_data.092916.csv
Traceback (most recent call last):
  File "/usr/local/bin/tpot", line 9, in <module>
    load_entry_point('TPOT==0.6.5', 'console_scripts', 'tpot')()
  File "/usr/local/lib/python2.7/site-packages/tpot/driver.py", line 179, in main
    input_data = np.recfromcsv(args.INPUT_FILE, delimiter=args.INPUT_SEPARATOR, dtype=np.float64, case_sensitive=True)
  File "/usr/local/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 1987, in recfromcsv
    output = genfromtxt(fname, **kwargs)
  File "/usr/local/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 1870, in genfromtxt
    output = np.array(data, dtype)
ValueError: invalid literal for float(): 0.499663797302258,0.951270682901906,0.127110095683095,0.469705611802261,0.188336271329,0.113829682230142,0.917617972625002,0.398412005963428,0.418909516500307,0.452983104638622,0.167462880835559,0.430

The data in numerai_training_data.092916.csv comes from the numer.ai site (retrieved on 9/29/2016). They make a file accessible at https://numer.ai/rules - click on the numerai_training_data.csv link.

The above output accords with the first line of data, which starts with these lines:

"feature1","feature2","feature3","feature4","feature5","feature6","feature7","feature8","feature9","feature10","feature11","feature12","feature13","feature14","feature15","feature16","feature17","feature18","feature19","feature20","feature21","target"
0.499663797302258,0.951270682901906,0.127110095683095,0.469705611802261,0.188336271329,0.113829682230142,0.917617972625002,0.398412005963428,0.418909516500307,0.452983104638622,0.167462880835559,0.430536195004487,0.137192382755926,0.201436783902082,0.507708366261194,0.919475403161345,0.978168970317083,0.177080430973426,0.101372329668598,0.722138422051696,0.832318863724542,0
0.0995146023475152,0.682824289132833,0.867939057661285,0.943827935986013,0.50552620186375,0.886766055285363,0.530862357899566,0.531001538177506,0.980001912438816,0.941858604062752,0.311849534849725,0.133232592505636,0.642639570301386,0.533367430388114,0.616878604427852,0.697038449283734,0.741461257825249,0.0866899514773392,0.109533043090749,0.324666240591188,0.552276376623551,1

Comparing the tpot output with the first data line, the output stops in the middle of the 12th value  - showing 0.430 for 0.430536195004487 - the rest of the data not output.

It looks like a buffer issue - is it one?

I upgraded numpy to version 1.11.2 - it still gave the same error.

I hope I have given enough information.

Regards

Colin Goldberg

**Comment by weixuanfu2016** [comment] 2016-10-08 13:50
Thank you for letting us know the question. The error is caused by no '-is' argument which is let tpot know the character used to separate columns in the input file. For your case, the setting should be '-is ,'. After you need let TPOT know which column is your target with '-target' argument. Please check [the manual for command line](http://rhiever.github.io/tpot/using/#tpot-on-the-command-line) to customize other arguments for running TPOT (I think it may cause some confusions when reading the `tpot /path_to/data_file.csv` on the top of the webpage). The right example is listed below the argument table on that webpage and also for your case, a example is listed below herein. Please test the command in your case.

Example :
## you can customize the setting (e.g. -o numerai_data_pipeline.py  -g 5 -p 20 -cv 5 -s 42 -v 2)
## numerai_training_data.092916.csv --> your input file
```
tpot numerai_training_data.092916.csv -is , -target target -o numerai_data_pipeline.py  -g 5 -p 20 -cv 5 -s 42 -v 2
```
#Output before running pipeline evalutation 
TPOT settings:
CROSSOVER_RATE	=	0.05
GENERATIONS	=	5
INPUT_FILE	=	numerai_training_data.csv
INPUT_SEPARATOR	=	,
MAX_EVAL_MINS	=	5
MAX_TIME_MINS	=	None
MUTATION_RATE	=	0.9
NUM_CV_FOLDS	=	5
OUTPUT_FILE	=	numerai_data_pipeline.py
POPULATION_SIZE	=	20
RANDOM_STATE	=	42
SCORING_FN	=	balanced_accuracy
TARGET_NAME	=	target
TPOT_MODE	=	classification
VERBOSITY	=	2

**Comment by colingoldberg** [comment] 2016-10-09 15:09
I added the maxeval 10 option, 

tpot numerai_training_data.092916.csv -is , -target target -o numerai_data_pipeline.py  -g 5 -p 20 -cv 5 -s 42 -v 2 -maxeval 10

It ran for just over an hour, until it stopped - at 13%, outputting the word "Killed"

TPOT settings:
CROSSOVER_RATE	=	0.05
GENERATIONS	=	5
INPUT_FILE	=	numerai_training_data.092916.csv
INPUT_SEPARATOR	=	,
MAX_EVAL_MINS	=	10.0
MAX_TIME_MINS	=	None
MUTATION_RATE	=	0.9
NUM_CV_FOLDS	=	5
OUTPUT_FILE	=	numerai_data_pipeline.py
POPULATION_SIZE	=	20
RANDOM_STATE	=	42
SCORING_FN	=	balanced_accuracy
TARGET_NAME	=	target
TPOT_MODE	=	classification
VERBOSITY	=	2

Timeout during evaluation of pipeline #1. Skipping to the next pipeline.                                                                                                       
Timeout during evaluation of pipeline #4. Skipping to the next pipeline.                                                                                                       
Timeout during evaluation of pipeline #5. Skipping to the next pipeline.                                                                                                       
Timeout during evaluation of pipeline #11. Skipping to the next pipeline.                                                                                                      
Timeout during evaluation of pipeline #12. Skipping to the next pipeline.                                                                                                      
Timeout during evaluation of pipeline #16. Skipping to the next pipeline.                                                                                                      
Optimization Progress:  13%|█████████████▋                                                                                         | 16/120 [1:12:21<9:18:51, 322.42s/pipeline]
Killed

I saw no files in the working directory - is there anywhere I can look for evidence? Any way to switch on logging?

I also am not sure about my option value for population size. I simply copied your value (20), but the total number of rows is 96321. Should I have set this value instead?

Regards

Colin Goldberg

**Comment by weixuanfu2016** [comment] 2016-10-09 16:46
I guess the issue was casued by out of stack or memory. For better understanding the issue, could you please let me know more details about the platform you used (e.g OS and maximum  memory size)?

You should not set a very large population size (like 200), which would cost a lot of computational resources than current one.

**Comment by colingoldberg** [comment] 2016-10-09 17:03
I ran it on an Amazon Web Services EC2 t2.small (Linux) instance, which means it has 2GB of memory (See https://aws.amazon.com/ec2/instance-types/).

**Comment by weixuanfu2016** [comment] 2016-10-10 19:42
I tested the dataset from the numer.ai website in my Linux platform and tracked the memory that the job used. The maximum memory it used was more than 2.5Gb (stdout below). 

```
Best pipeline: LogisticRegression(RobustScaler(input_matrix), 0.83000000000000007, 70, False)

Training score: 0.521944204827
Holdout score: 0.523094000072
	Command being timed: "tpot numerai_training_data.csv -is , -target target -o numerai_data_pipeline.py -g 5 -p 20 -cv 5 -s 42 -v 2 -maxeval 10"
	User time (seconds): 7212.62
	System time (seconds): 84.39
	Percent of CPU this job got: 113%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:47:13
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 2545820
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 4806497
	Voluntary context switches: 494145
	Involuntary context switches: 67974874
	Swaps: 0
	File system inputs: 0
	File system outputs: 64
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```

**Comment by rhiever** [comment] 2016-12-19 20:07
Should we count this issue as resolved since @weixuanfu2016 added the PR to the `development` branch to fix the solver issue?

**Comment by rhiever** [comment] 2017-03-21 21:11
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.

**Closed by rhiever** 2017-03-21 21:11 UTC
Labels: question
