### ISSUE TITLE
version 0.6.7 abnormally terminates prior to completion with error "Cputime limit exceeded: 24"

### ISSUE THREAD

**Issue by scottcha** [rhiever/tpot#300] opened 2016-11-01 04:03 UTC
Using same inputs and script which worked in 0.6.6 I now receive "Cputime limit exceeded: 24" during fit operation.

## Context of the issue

This is relevant as it seems to be an internal error which has been introduced with this new version of TPot.

## Process to reproduce the issue
#use input file located here: https://1drv.ms/u/s!Agy-WTdBusDXndslUdhBWppnUn06xg
Code to reproduce:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import numpy as np

avyDataAll = pd.read_csv('./filteredFeaturesForTPotV5.csv')
avyDataX = avyDataAll.ix[:, avyDataAll.columns != 'class'].values
avyDataY = avyDataAll.ix[:, avyDataAll.columns == 'class'].values

X_train, X_test, y_train, y_test = train_test_split(avyDataX, avyDataY,
                                                    train_size=0.75, test_size=0.25, stratify=avyDataY)

tpot = TPOTClassifier(generations=3, verbosity=2) 
tpot.fit(features=X_train, classes=y_train[:,0]) #fails on this line
print(tpot.score(X_test, y_test[:,0]))

## Expected result
Version 0.6.6 of tpot is outdated. Version 0.6.7 was released 5 days ago.
Timeout during evaluation of pipeline #11. Skipping to the next pipeline.                                               
Generation 1 - Current best internal CV score: 0.7432473521247461                                                       
Generation 2 - Current best internal CV score: 0.7432473521247461                                                       
Generation 3 - Current best internal CV score: 0.7432473521247461                                                       
                                                                                                                        
Best pipeline: LogisticRegression(input_matrix, 0.13, 35, False)
0.687315151813

## Current result
(py35)Scotts-MacBook-Pro-2: scottcha$ python forecastTpot.py 
Optimization Progress:  23%|████████████▏                                        | 92/400 [03:03<16:53,  3.29s/pipeline]**Cputime limit exceeded: 24**

**Comment by weixuanfu2016** [comment] 2016-11-01 20:16
Thank you for letting us know the issue. I tried to the codes and dataset in my macbook pro with this latest OSX but the error cannot be reproduced. 

My first guess about this issue is that the CPU time limit failed to reset during pipeline evaluation somehow. But it is strange because if CPU time limit failed to reset then this expectation signal  should not be available either, since this `SIGXCPU` (Cputime limit exceeded: 24) should be replaced by `RuntimeError` during pipeline evaluation.

For better reproducing the issue, could you please try the codes again with setting a few random seeds (e.g. put `random_state=99` in the `TPOTClassifier` function in the codes)? If the error happen again, please let us know the update codes with these random seeds

Meanwhile, I can try more instances to reproduce the error.

**Comment by scottcha** [comment] 2016-11-02 01:31
Tried again with random_state=99 and it still repros. 

(py35)Scotts-MacBook-Pro-2: scottcha$ python AvyForecastTpot.py 
Optimization Progress:  17%|████████▉                                            | 67/400 [02:15<14:50,  2.67s/pipeline]Cputime limit exceeded: 24

**Comment by weixuanfu2016** [comment] 2016-11-02 16:20
After a few tests on your datasets, I think I may find the reason of this issue. It seems not related to version of TPOT you used. It is about memory and a particular pipeline. 

Try the codes below. it should reproduce the issue with both your datasets and simulation datasets.

We will try to limit memory usage of pipeline to avoid this issue in the future version of TPOT.

To avoid this issue in the current version of TPOT, please try to clean your memory in the platform (e.g quit some apps using a lot of memory, like Chrome). 

```
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import make_pipeline, make_union
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures, FunctionTransformer
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
import pandas as pd

X, y = make_classification(n_samples=200, n_features=800,
                                    n_informative=2, n_redundant=10,
                                    random_state=42)

avyDataAll = pd.read_csv('./filteredFeaturesForTPotV5.csv')
avyDataX = avyDataAll.ix[:, avyDataAll.columns != 'class'].values
avyDataY = avyDataAll.ix[:, avyDataAll.columns == 'class'].values

X_train, X_test, y_train, y_test = train_test_split(avyDataX, avyDataY,
train_size=0.75, test_size=0.25, stratify=avyDataY)



fa_make = make_pipeline(
    make_union(
        FunctionTransformer(lambda X: X),
        FunctionTransformer(lambda X: X)
    ),
    PolynomialFeatures(),
    LogisticRegression()
)

# !!!!!dataset in issue 300 need at least 2.5Gb Memory 
fa_make.fit(X_train,y_train[:,0])


# !!!!!simulation dataset need at least 4Gb Memory 
fa_make.fit(X,y)

```

**Comment by scottcha** [comment] 2016-11-03 04:26
I tried your test pipeline 4 times all passed without error.  It did increase memory usage but never to the point where free memory was an issue on my 16GB MBP.

I ran several more instances of TPOT tonight and it definitely seems to fail in this case with light memory usage < 150MB for the process (7GB free on the system).  

Any recommendation about how I might get tpot to output every pipeline it's evaluating when it's evaluating such that we can narrow it down to a potential issue like you suggested or other suggestions for profiling?

**Comment by weixuanfu2016** [comment] 2016-11-03 14:38
[tpot_debug_for_issue300.tar.gz](https://github.com/rhiever/tpot/files/569232/tpot_debug_for_issue300.tar.gz)

Please download my tweaked version of TPOT based on 0.6.7 above. Your dataset and codes are also in the compressed file. You can use the codes below to get a debug log when running a instance. Please send over the log file once the issue reproduces in your platform. Thanks.
```
tar -zxvf tpot_debug_for_issue300.tar.gz 
cd tpot
python issue_300.py 
```

**Comment by scottcha** [comment] 2016-11-04 17:21
Here is the 2 log outputs from your debug tpot.  Both failed with the same error.
[TPOT_debug_log_2016-11-04-10:05:06.957318.txt](https://github.com/rhiever/tpot/files/572200/TPOT_debug_log_2016-11-04-10.05.06.957318.txt)
[TPOT_debug_log_2016-11-04-10:18:23.950857.txt](https://github.com/rhiever/tpot/files/572201/TPOT_debug_log_2016-11-04-10.18.23.950857.txt)

**Comment by weixuanfu2016** [comment] 2016-11-07 19:15
Thank you for providing this log files. Finally, after a lot of tests, we found the bug. I already posted a hot patch #306 for dealing with this issue.

Please test this codes below, it should reproduce the issue randomly in macOS. Please let us know if it cannot be reproduced.

Some operators from scikit-learn seems not works with  resource.setrlimit in MacOS (from version 10.11.2 - 10.12.1). But there is not this kind of issue in Linux OS (I tested 100 instances with your dataset and codes in multiple Linux platforms). Before we merge the PR#306 with TPOT, please run the current version of TPOT in a Linux platform. Sorry for the inconvenient. 


```
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB
from resource import getrlimit, setrlimit, RLIMIT_CPU, getrusage, RUSAGE_SELF, RUSAGE_CHILDREN

class TIMEOUT(RuntimeError):
    """
    Inhertis from RuntimeError
    """
    pass

def timeout_signal_handler(signum, frame):
    """
    signal handler for _timeout function
    rasie TIMEOUT exception
    """
    raise TIMEOUT("Time Out!")


X, y = make_classification(n_samples=200, n_features=80,
                                    n_informative=2, n_redundant=10,
                                    random_state=42)


classifor_list = {#"ExtraTreesClassifier": ExtraTreesClassifier, # pass
                    "LogisticRegression": LogisticRegression, # fail
                    #"MultinomialNB": MultinomialNB, # pass
                    #"GaussianNB": GaussianNB, # pass
                    "BernoulliNB": BernoulliNB # fail
                }



for key in classifor_list.keys():
    clf = classifor_list[key]()
    for i in range(300):
        if i == 0:
            print(key)
        print("test #",i+1,'for',key)
        r = getrusage(RUSAGE_SELF)
        cpu_time = r.ru_utime + r.ru_stime
        r_child = getrusage(RUSAGE_CHILDREN)
        child_time = r_child.ru_utime + r_child.ru_stime
        current = getrlimit(RLIMIT_CPU)
        print('Main_cpu_time used: {} | child_cpu_time used: {}\n'.format(cpu_time, child_time))
        print('cpu_time_limit: {}'.format(current))
        try:
            setrlimit(RLIMIT_CPU, (cpu_time+300, current[1]))
            clf.fit(X,y)
            cv_scores = cross_val_score(clf, X, y)
        except Exception as e:
            print('some thing wrong',e)
        finally:
            setrlimit(RLIMIT_CPU, current)
```

**Comment by weixuanfu2016** [comment] 2016-11-08 15:06
Increasing `n_features` (e.g `n_features=800`) will reproduce the issue more quickly. I tested it on 2 Macbook Pro on different version of MacOS. But a more strange thing is that this codes is running all right in my Macbook Air.

**Comment by rhiever** [comment] 2017-03-21 21:08
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.

**Closed by rhiever** 2017-03-21 21:08 UTC
Labels: question
