### ISSUE TITLE
Is it possible to add "early stopping" in case the accuracy pass a specific value.

### ISSUE THREAD

**Issue by drorhilman** [rhiever/tpot#539] opened 2017-07-30 08:37 UTC
Question: 
TPOT runs can be very long for large population, but sometime you reach a very high accuracy early-on, and you would like the process to stop if it is not improving after a while. is it possible to do it? 
For example if it reaches 99% accuracy and not improving in 3 generation then stop.

**Comment by weixuanfu** [comment] 2017-07-31 14:14
Hmm, I think we might add this option once the accuracy of classification reaches a very high score, like 0.999. What do you think of this idea? @rhiever 

But I think it is not simply to use the option in most of scoring functions in regression tasks.

**Comment by drorhilman** [comment] 2017-08-02 04:01
Yes. I think that it should have a notion of "progress" - check whether you are still improving or not, and if not then stop.

**Comment by weixuanfu** [comment] 2017-08-02 14:28
If the option just check whether the best pipeline is still improving in GP, this option maybe misused with small number of population size due to limited number of new better individuals per generation. I think we still need a threshold value if we add this option.

**Comment by weixuanfu** [comment] 2017-08-03 14:46
@drorhilman after some discussions with @rhiever, we will add this option to stop process if the score does not improve after N generations. The option will be added into next version of TPOT and of course, it is turned off by default.

**Comment by weixuanfu** [comment] 2017-08-04 17:26
Update: We added this option in the PR #541 and it should be merged later.

**Closed** 2017-09-08 13:34 UTC
Labels: enhancement
