### ISSUE TITLE
Regressor in a VotingClassifier?

### ISSUE THREAD

**Issue by pealco** [rhiever/tpot#457] opened 2017-05-19 22:33 UTC
After fitting a `TPOTRegressor`, TPOT returns a model that looks like this:

```
exported_pipeline = make_pipeline(
    make_union(VotingClassifier([("est", KNeighborsRegressor(n_neighbors=19, p=1, weights="distance"))]), FunctionTransformer(copy)),
    VarianceThreshold(threshold=0.7000000000000001),
    make_union(VotingClassifier([("est", RidgeCV())]), FunctionTransformer(copy)),
    ExtraTreesRegressor(max_features=0.05, min_samples_leaf=20, min_samples_split=3, n_estimators=100)
)
```

I'm a bit confused about what it means to wrap a `VotingClassifier` around a regressor. I would usually expect to pass it a set of classifiers (I haven't been able to find instances of people using the `VotingClassifer`/regressor combination after some googling, either). I thought that maybe since there's only one object being passed into the `VotingClassifier`, it would just pass through transparently and I could just ignore it. This does not seem to be the case. The `VotingClassifier` transforms the output of the regressor somehow.

1. What does it mean to pass a regressor to a `VotingClassifer`?
2. If `VotingClassifer` is not intended to be used this way, should TPOT avoid using it in regression problems?

**Comment by weixuanfu2016** [comment] 2017-05-20 00:41
The purpose of the`make_union(VotingClassifier(.... FunctionTransformer...))` in the codes is that if one step in a pipeline is an estimator and is not the last step then we must add its guess as a synthetic feature. 

Like you mentioned, `VotingClassifier ` is not designed for regressor but somehow it could pass the prediction as a synthetic feature to next steps. I think we need run some tests before deciding if TPOT should avoid using `VotingClassifier`in regression program.

The issue is related to #214

**Comment by weixuanfu2016** [comment] 2017-05-20 01:20
Thank you for letting us know this issue. I use the codes below to check if `VotingClassifier` also works for regressor. Sadly, it did not work as excepted. We may need avoid `VotingClassifier` in `TPOTRegressor ` or make a `VotingRegessor` in TPOT.
```
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.datasets import make_regression, make_classification
from sklearn.metrics import r2_score, accuracy_score
from sklearn.pipeline import make_pipeline, make_union
from sklearn.preprocessing import FunctionTransformer
from copy import copy

print('Test Regression')

reg1 = LinearRegression()

X, y = make_regression(n_samples=50, n_features=5, random_state=0)

ereg1 = make_pipeline(make_union(VotingClassifier(estimators=[
        ('lr', LinearRegression())], voting='hard'), FunctionTransformer(copy)))

ereg1.fit(X, y)
reg1.fit(X,y)
print('Regressor out of pipeline', r2_score(y, reg1.predict(X)))
print('Regressor in pipeline',r2_score(y, ereg1.transform(X)[:,0]))
print('If the synthetic feature is the predict y in regressor: ', np.allclose(reg1.predict(X), ereg1.transform(X)[:,0]))

print('Test Classifcation')
clf1 = LogisticRegression()
X, y = make_classification(n_samples=50, n_features=5, random_state=0)
eclf1 = make_pipeline(make_union(VotingClassifier(estimators=[
        ('lr', LogisticRegression())], voting='hard'), FunctionTransformer(copy)))

eclf1.fit(X, y)
clf1.fit(X,y)
print('Classifier out of pipeline', accuracy_score(y, clf1.predict(X)))
print('Classifier in pipeline', accuracy_score(y, eclf1.transform(X)[:,0]))
print('If the synthetic feature is the predict y in classifier: ', np.allclose(clf1.predict(X), eclf1.transform(X)[:,0]))

```

Output:
```
Test Regression
Regressor out of pipeline 1.0
Regressor in pipeline 0.188336862313
If the synthetic feature is the predict y in regressor:  False
Test Classifcation
Classifier out of pipeline 0.98
Classifier in pipeline 0.98
If the synthetic feature is the predict y in classifier:  True
```

**Comment by rhiever** [comment] 2017-05-20 11:03
As @weixuanfu2016 mentioned, we use the VotingClassifier to [stack](https://www.quora.com/What-is-stacking-in-machine-learning) intermediate classifiers in TPOT pipelines. As @weixuanfu2016 pointed out, VotingClassifier doesn't seem to work quite as expected with regression models.

Regardless, TPOT seems to have found that stacking a couple regression models' predictions improves the predictive performance of your model, even if the outputs aren't continuous from the VotingClassifier. You can validate this claim by comparing your original pipeline's score to this one:

```python
exported_pipeline = make_pipeline(
    VarianceThreshold(threshold=0.7000000000000001),
    ExtraTreesRegressor(max_features=0.05, min_samples_leaf=20, min_samples_split=3, n_estimators=100)
)
```

We'll have to look into this issue deeper. I'll file this as a bug report for now. Thank you.

**Comment by weixuanfu2016** [comment] 2017-05-20 11:17
@rhiever  the outputs from the `VotingClassifier` are continuous when running with regressors, but not the right prediction of y. It is very weird. I think `VotingClassifier` should raise warning message when running with regressor.

**Comment by weixuanfu2016** [comment] 2017-05-20 11:27
@rhiever I found two replacements for stacking classifiers or regressors. Check the links below:

[StackingClassifier](https://rasbt.github.io/mlxtend/user_guide/classifier/StackingClassifier)
(StackingRegressor)(https://rasbt.github.io/mlxtend/user_guide/regressor/StackingRegressor)

**Comment by rhiever** [comment] 2017-05-20 11:33
Rather than adding a new dependency (even if it's a nice one, @rasbt ;-) ), could we port the underlying code for those stacking models to TPOT? I think it's realistically only something like [this](https://github.com/rasbt/mlxtend/blob/5d9938626fe98ff26ce89fbd0ae0557619864630/mlxtend/regressor/stacking_regression.py#L134).

**Comment by weixuanfu2016** [comment] 2017-05-20 11:36
Sounds good and thank you for the nice tool @rasbt

**Comment by rasbt** [comment] 2017-05-20 14:11
The code for the StackingRegressor/Classifier is indeed super simple. You could either port it or just put it under an `tpot/external` path like they do in scikit-learn with joblib, [for example](https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/externals) to avoid additional external dependencies; mlxtend is under an MIT license, which should be compatible with GNU/GPL.

Regarding the StackingClassifier, I would maybe recommend to also (or instead) consider the [StackingCVClassifier](http://rasbt.github.io/mlxtend/user_guide/classifier/StackingCVClassifier/), which is a bit more robust when it comes to overfitting :)

**Comment by rhiever** [comment] 2017-05-20 14:50
I'm 👍 on porting in the stacking classifier/regressor into an `external` directory.

TPOT should be handling the CV, so no need to use the CV version.

**Comment by rasbt** [comment] 2017-05-20 16:14
Cool! 
> TPOT should be handling the CV, so no need to use the CV versions IMO.

I think it's a bit different in this context from what TPOT is doing with CV. Here, it's an internal way of doing CV between the 1st & 2nd level classifiers (not a wrapper around the classifier). Basically, the 2nd level classifier gets different features from the 1st level classifier here:

> In the standard stacking procedure, the first-level classifiers are fit to the same training set that is used prepare the inputs for the second-level classifier, which may lead to overfitting. The StackingCVClassifier, however, uses the concept of cross-validation: the dataset is split into k folds, and in k successive rounds, k-1 folds are used to fit the first level classifier; in each round, the first-level classifiers are then applied to the remaining 1 subset that was not used for model fitting in each iteration. The resulting predictions are then stacked and provided -- as input data -- to the second-level classifier. After the training of the StackingCVClassifier, the first-level classifiers are fit to the entire dataset

![stacking_cv_algorithm](https://cloud.githubusercontent.com/assets/5618407/26277457/d5da24d2-3d55-11e7-90cb-b9d892131a50.png)

**Comment by weixuanfu2016** [comment] 2017-05-22 18:29
@rasbt Thank you for sharing the way of CV in `StackingCVClassifier`. But I think the pipelines in TPOT stack only one estimator as a step to add synthetic feature(s) into transformed X. So I reimplement the Stacking class based on the codes in your tools and simplified it as a transformer by removing meta-estimator. I put the transformer into the PR #460

**Comment by rhiever** [comment] 2017-05-23 19:43
Fixed in the latest dev branch.

**Closed by rhiever** 2017-05-23 19:43 UTC
Labels: bug, help wanted
