### ISSUE TITLE
struct.error in fit() 

### ISSUE THREAD

**Issue by nick-magnini** [rhiever/tpot#413] opened 2017-04-11 02:36 UTC
I get this error after I run the fit() function for this:
tpot = TPOTClassifier(verbosity=3, n_jobs=8, random_state=1, cv=5, generations=50, population_size=100)
```
~/anaconda3/envs/tpot/lib/python3.4/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module 
was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved.
 Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.  
  "This module will be removed in 0.20.", DeprecationWarning)                                                                       
^MOptimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]30 operators have been imported by TPOT.                      
start learning models...                                                                                                            
_pre_test decorator: _generate: num_test=0 k should be >=0, <= n_features; got 76.Use k='all' to return all features.               
_pre_test decorator: _generate: num_test=1 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' ar
e not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True                                           
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' ar
e not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True                                           
_pre_test decorator: _generate: num_test=0 Found array with 0 feature(s) (shape=(50, 0)) while a minimum of 1 is required.          
_pre_test decorator: _generate: num_test=1 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 max_features must be in (0, n_features]                                                  
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='hinge' is not sup
ported, Parameters: penalty='l1', loss='hinge', dual=True                                                                           
_pre_test decorator: _generate: num_test=0 Found array with 0 feature(s) (shape=(50, 0)) while a minimum of 1 is required.          
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=1 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='logistic_regressi
on' are not supported when dual=True, Parameters: penalty='l1', loss='logistic_regression', dual=True                               
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 k should be >=0, <= n_features; got 52.Use k='all' to return all features.               
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' ar
e not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True                                           
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' ar
e not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True                                           
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 max_features must be in (0, n_features]                                                  
_pre_test decorator: _generate: num_test=1 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='hinge' is not sup
ported, Parameters: penalty='l1', loss='hinge', dual=True                                                                           
_pre_test decorator: _generate: num_test=0 precomputed was provided as affinity. Ward can only work with euclidean distances.       
Invalid pipeline encountered. Skipping its evaluation.                                                                              
                    Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]Optimization Progress:  55%|#####5
    | 55/100 [03:22<02:45,  3.68s/pipeline]Optimization Progress: 100%|##########| 100/100 [05:04<00:00,  3.26s/pipeline]      
                                                                       Traceback (most recent call last):                         
  File "training_tpot.py", line 181, in <module>                                                 
    tpot.fit(X_train, y_train)                                                         

tpot.fit(X_train, y_train)                                                                                                      
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/tpot/base.py", line 413, in fit                         
    verbose=self.verbosity, max_time_mins=self.max_time_mins)                                                                       
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/tpot/gp_deap.py", line 138, in eaMuPlusLambda           
    fitnesses = toolbox.evaluate(invalid_ind)                                                                                       
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/tpot/base.py", line 747, in _evaluate_individuals       
    resulting_score_list = [-float('inf') if x == 'Timeout' else x for x in list(res_imap)]                                         
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/multiprocess/pool.py", line 698, in next                
    raise value                                                                                                                     
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/multiprocess/pool.py", line 385, in _handle_tasks       
    put(task)                                                                                                                       
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/multiprocess/connection.py", line 209, in send          
    self._send_bytes(ForkingPickler.dumps(obj))                                                                                     
  File "~/anaconda3/envs/tpot/lib/python3.4/site-packages/multiprocess/connection.py", line 402, in _send_bytes   
    header = struct.pack("!i", n)                                                                                                   
struct.error: 'i' format requires -2147483648 <= number <= 2147483647    
```

**Comment by weixuanfu2016** [comment] 2017-04-11 04:21
Hmm, I have not seen this error message before. Could you please let me know more details about the environment and datasets, like the total numbers of samples and features and how many GB memory your computer has?

I suspect the error is caused by luck of memory when pickling objects in multiprocessing. Could you please also try to use lower number of `n_jobs`, like `n_jobs=2` for a test?

**Comment by nick-magnini** [comment] 2017-04-11 05:14
I think the problem is memory since when I decreased the sample size to 1000 then it could run with no error. However, the machine has 200gb available memory. The number of examples is around 70000, with around 20-25k features concatenated together with np.hstack.

**Comment by weixuanfu2016** [comment] 2017-04-11 05:32
How about running with n_jobs =2?

**Comment by nick-magnini** [comment] 2017-04-11 05:42
Same error with n_jobs =2

**Comment by weixuanfu2016** [comment] 2017-04-11 11:07
Hmm, could you please try the dev version of tpot in development branch? It is noted that the dev version is not fully tested yet but it used `joblib` to replace `pathos` module for parallel computing related to the `n_jobs` parameter. I am curious whether the dev is better for large dataset.

Please try the commands below for installing the dev version.

```
pip uninstall tpot
pip install git+https://github.com/rhiever/tpot.git@development
```

**Comment by rhiever** [comment] 2017-04-20 13:37
Any updates on this issue, @nick-magnini?

**Comment by rhiever** [comment] 2017-04-24 19:05
Closing this issue for now. Please re-open if the issue persists.

**Closed by rhiever** 2017-04-24 19:05 UTC
Labels: question

**Comment by nick-magnini** [comment] 2017-04-24 22:10
Alright. I was running few experiments to figure out this issue for a better description. The summary of findings:

1) If I run with n_jobs=2 and much fewer features with `TPOTClassifier(verbosity=3, n_jobs=2, random_state=1, cv=4, generations=5, population_size=10, scoring='f1_micro')` then I'm able to get results.

2) If I run with n_jobs=8 and more features with `TPOTClassifier(verbosity=3, n_jobs=10, random_state=1, cv=4, generations=10, population_size=50, scoring='f1_micro')` then still after few days I'm not getting to any results. I ran the dataset with normal classifiers and maximum time for training and testing was 60 mins using sklearn while some classifiers were done in less than 5-10 mins. This is my log after couple of days:
```
Optimization Progress:   0%|          | 0/550 [00:00<?, ?pipeline/s](70409, 22197)                                                  
(70409,)                                                                                                                            
Version 0.7.0 of tpot is outdated. Version 0.7.2 was released 9 hours ago.                                                          
30 operators have been imported by TPOT.                                                                                            
start learning models...                                                                                                            
_pre_test decorator: _generate: num_test=0 k should be >=0, <= n_features; got 76.Use k='all' to return all features.               
_pre_test decorator: _generate: num_test=1 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' ar
e not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True                                           
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 Expected n_neighbors <= n_samples,  but n_samples = 50, n_neighbors = 97                 
_pre_test decorator: _generate: num_test=0 Input X must be non-negative                                                             
_pre_test decorator: _generate: num_test=0 k should be >=0, <= n_features; got 67.Use k='all' to return all features.               
Invalid pipeline encountered. Skipping its evaluation.                                                                              
Optimization Progress:   0%|          | 0/550 [00:00<?, ?pipeline/s]
```

**Comment by rhiever** [comment] 2017-04-25 18:16
As a quick test: What if you use the TPOT light configuration? http://rhiever.github.io/tpot/using/#built-in-tpot-configurations
